DROP EXTENSION IF EXISTS pgcrypto CASCADE;

DROP FUNCTION IF EXISTS encrypt_password(TEXT) CASCADE;
DROP FUNCTION IF EXISTS check_password(TEXT, TEXT) CASCADE;

DROP TABLE IF EXISTS profile CASCADE;

DROP PROCEDURE IF EXISTS create_profile(TEXT, TEXT, TEXT) CASCADE;
DROP PROCEDURE IF EXISTS update_profile(BIGINT, TEXT, TEXT, TEXT) CASCADE;
DROP PROCEDURE IF EXISTS delete_profile(BIGINT) CASCADE;

DROP FUNCTION IF EXISTS get_profile(BIGINT) CASCADE;
DROP FUNCTION IF EXISTS get_profile_id(TEXT, TEXT) CASCADE;
DROP FUNCTION IF EXISTS get_all_profiles(INTEGER, INTEGER);
